### ISSUE TITLE
ultra newbie help

### ISSUE THREAD

**Issue by jkimyoung** [MagerValp/AutoDMG#104]
I am trying to find out the best set of open source tools for use with Casper. All the ones I am looking at are on GitHub so it seems like that is the place to go to get thoughts on the various tools but it seems like all the communications are set up for bug reports or code submissions. Is this the right place to be to ask general questions about things like autoDMG or autoPKG?

Thanks.

**Comment by jazzace** [comment]
On Feb 27, 2015, at 9:47 AM, jkimyoung <notifications@github.com> wrote:

> I am trying to find out the best set of open source tools for use with Casper. [�] Is this the right place to be to ask general questions about things like autoDMG or autoPKG?


The short answer: no.

I would start with JAMF Nation, since it is the discussion board for Casper users:

   https://jamfnation.jamfsoftware.com/

AutoPkg has a discussion list in Google Groups:

   https://groups.google.com/forum/#!forum/autopkg-discuss

Finally, there is always the MacEnterprise list, but do search the list archive first before asking a question, as that is one of the operating principles of that list:

   http://lists.psu.edu/archives/macenterprise.html

I do think you are on the right track by looking at AutoDMG and AutoPkg, though. :-)


Anthony Reimer
University of Calgary

**Comment by donmontalvo** [comment]
There's also the ##osx-server IRC:

https://groups.google.com/d/msg/macenterprise/jK3qv1DZXzk/4hCHvX1xttQJ

**Comment by jkimyoung** [comment]
Thanks very much for the info. I did watch your DMV presentation and it
gave me a good orientation. Very well done.

Regards,

Kim Young
MS laptop technician
Packer Collegiate Institute
170 Joralemon Street
Brooklyn, NY  11201
(718) 250-0217

On Fri, Feb 27, 2015 at 12:00 PM, MagerValp/AutoDMG <
reply@reply.github.com
> wrote:

>

**Comment by donmontalvo** [comment]
(fyi @jkimyoung is referring to @jazzace)
