### ISSUE TITLE
Feature Request: drag and drop templates.

### ISSUE THREAD

**Issue by mark-cohen** [MagerValp/AutoDMG#139]
Currently, in order to add templates, the Image's .adtmpl file has to be manually edited. 
Being able to drag and drop templates into the GUI would be a time saver.

Thanks.

**Comment by MagerValp** [comment]
I have a hard time picturing how the feature would work. Could you describe it in more detail, including how the GUI would react?

**Comment by mark-cohen** [comment]
Drag *.adtmpl file(s) into lower pane ("Additional software") of GUI, just as with additional packages. This would avoid having to save (thereby creating a template) and then edit the resulting (saved) template (with a text editor) to add the desired additional .adtmpl files. 

Thanks.

**Comment by jazzace** [comment]
Since you can include templates within other templates by reference, the functionality Mark wants is already available (and, indeed, is more flexible) if you are willing to edit the adtmpl file. It's just not available in the GUI.

The change to the GUI Mark is suggesting is only really possible by a fundamental rethink of how templates currently work. For example, one way it could work is if the GUI actually displayed the hierarchy of included templates (using folders and disclosure triangles) such that dragging a template file onto the Additional Software area would add the packages from that payload in a new folder in the list. (In that situation, I would also suggest that AutoDMG ignore references in the template to the OS Installer and the choice of whether to include updates or not, as that conflict would need to be addressed.) Should the user then choose to save the template, it would include a reference to the template rather than a list of the contents.

The current behaviour is for AutoDMG to parse for Additional Software from a single template (which can have references to others) and then put all the payload items in a sequential list. Should the user then save the template, all of the underlying template references would be overwritten by a single list of items. This is the reason my most important base templates are a single reference to an included template, in case I accidentally save over that template and don't have a recent backup.

Honestly, I would prefer it if Additional Packages could work more like a Finder list window, where I could then create folders (i.e. include templates), move things from folder to folder, add existing folders/templates of additional files, and then save them in the GUI with the all the included template files referenced within that adtmpl file. But I completely understand that 90% of the people who are using AutoDMG only put a few payload items in their image, like hooks to Munki and a local user or two. It is also what Per had in mind when he built the tool. The fact that he brought over virtually all of the features of InstaDMG — which was a command line + text file tool — allowed me to keep my "thicker" modular build workflow if I so chose, even though that wasn't the intent of the tool.

So if someone wants to rewrite that part of the code — and it would be a substantial rewrite — I'm in favour of that, but I'm not sure it's worth the effort, since the days of thick images are gone for most of us. For those who continue to have reasons to ship larger images (e.g., Logic Pro X sound libraries), editing plists is not a high barrier to traverse.

**Comment by mark-cohen** [comment]
I dont want to deter from the excellent work done on this invaluable tool, and completely agree with Anthony, that such a feature is likely unjustifiable - due to all the aforementioned reasons.

**Comment by MagerValp** [comment]
It's still not quite clear to me how this would work, but I'm also picturing something along the lines of a hierarchical Finder view. This is way beyond both the time I have available for AutoDMG and my current Cocoa skills, so plist editing is the way it'll have to be for now.

A better approach might be to make a separate template editing app if someone else wants to take a stab at it.
