### ISSUE TITLE
iTunes 12.7

### ISSUE THREAD

**Issue by cem62793** [MagerValp/AutoDMG#196]
## Description of issue

The latest release of autodmg doesn't allow the latest version of iTunes to be installed as part of an image build.

**Comment by arubdesu** [comment]
Hello @cem62793 and welcome to GitHub!
This wouldn’t be the applicable repo to report this issue, and you’re reporting it as if it’s not intentional/a mistake. Please see here for when this decision was made:
https://github.com/MagerValp/AutoDMGUpdateProfiles/commit/e29d64e2440d16868b44463b1ee1e0ea82153347

**Comment by MagerValp** [comment]
Apple broke the 12.7 update on 10.12, so it can't be installed until they release a fix.
