### ISSUE TITLE
Build on mismatched system

### ISSUE THREAD

**Issue by STLVNUB** [MagerValp/AutoDMG#245]
## Description of issue

Can we have experimentally support to build different versions
i.e High Sierra on Catalina
Seems silly to me to build Catalina on Catalina
## Expected behavior

bar

## Actual behavior

baz

## Steps to reproduce

1. xxx
2. yyy
3. zzz

## Log file

_(Save the debug log and attach it by dragging it here)_

**Comment by arubdesu** [comment]
Hey @STLVNUB, it's literally [FAQ number 1](https://github.com/MagerValp/AutoDMG/wiki/FAQ#1-can-i-build-images-for-one-os-while-running-another) that it's not supported, but you're free to develop and contribute this feature yourself, I'm sure everyone else would find valuable as well. I'd also think that since AutoDMG is relying on the running operating systems frameworks for things like asr and installer, you'd need to start vendoring those binaries/frameworks and ship all of them to each OS you want to support building on, and add logic to select between them.
