### ISSUE TITLE
Volume Name Persistency, Not Saving to .adtmpl (OS X 10.10.1 Yosemite, AutoDMG 1.5.2)

### ISSUE THREAD

**Issue by pcrandom** [MagerValp/AutoDMG#96]
I've noticed that a custom Volume Name, specified in the Advanced Options dialog, is not persistent from session to session.  If I specify "autodmg" as the Volume Name, quit AutoDMG and relaunch AutoDMG, the Volume Name field is blank again ("Macintosh HD" by default).

Futhermore, if I save a build configuration, even if I specify a custom Volume Name in Advanced Options beforehand, the .adtmpl file generated still contains the default setting:
```
<key>VolumeName</key>
<string>Macintosh HD</string>
```
Clarification:  If I specify a custom volume name and save the build configuration, even though the .adtmpl file does not contain the custom name, the current running session of AutoDMG still has the name in Advanced Options and will build an image with the specified name.  The issue comes when I've quit AutoDMG, later opening the .adtmpl file again, assuming my custom volume name is intact, when it has reverted to "Macintosh HD".

I have to manually edit the .adtmpl file to change the volume name, after which, if I load the template, then Advanced Options shows the proper custom volume name as expected.

However, if I save the build configuration again in AutoDMG, even if Advanced Options still has the custom Volume Name, the .adtmpl file reverts to the default setting.  I don't even have to make any changes to the build configuration first.  I just have to hit Command+S in AutoDMG after opening a .adtmpl file, and the keys change from
```
<key>VolumeName</key>
<string>autodmg</string>
```
back to 
```
<key>VolumeName</key>
<string>Macintosh HD</string>
```

As for why I want to change the volume name, I've encountered some problems building images when the volume name has a space in it.  Coming from InstaDMG, where the default volume name is "instadmg", it took a little digging to find out why certain packages would install fine in InstaDMG but not AutoDMG.

It's almost always a pre/post-install/flight script of some sort that doesn't use $3 or have quotation marks around paths.  It's not too bad when the scripts error out, which reminds me to either try to fix the script or to rename the volume name, but certain scripts *cough*Cisco AnyConnect VPN module postinstall*cough* don't error out, and I don't discover any issues with the image until much later.

Of course, this isn't AutoDMG's problem, but is a hassle that can be avoided by using a volume name without spaces.  Unfortunately, AutoDMG seems keen on wanting me to use "Macintosh HD" for my volume name.  :-)

**Comment by jazzace** [comment]
"I've noticed that a custom Volume Name, specified in the Advanced Options dialog, is not persistent from session to session."

Per can correct me if I'm wrong, but this is by design. If it was meant to persist, the setting would be under AutoDMG > Preferences, not Window > Advanced Options. If you think that this should be a new feature, I'd suggest you submit a separate issue for it. Alternately, you could just set up a template file that sets the Volume Name to your preferred value (no OS or additional packages required) and open it when you want to create a new image.

As for the bug you are reporting, I can repeat it on 10.9.5 as well:

1. Open AutoDMG.
2. Using Advanced Options, change the Volume Name.
3. Save this as a template.

The template file will have the VolumeName as the default (Macintosh HD), not the one specified in the GUI.

**Comment by pcrandom** [comment]
@jazzace, I figure the non-persistency was by design; I was just setting the stage, so to speak.  :-)  Not necessarily interested in it as a feature request, but it's something to keep in mind when using AutoDMG.  I do like your idea for a "default" template that I would open so it always had the setting that I want.

**Comment by MagerValp** [comment]
Lack of GUI persistence is by design, but a custom volume name should certainly be saved to the .adtmpl.

**Comment by MagerValp** [comment]
Please try [AutoDMG 1.5.3b387](https://www.dropbox.com/s/9vrnfukfsg5tep0/AutoDMG-1.5.3b387.dmg).
